---
- hosts: localhost 
  gather_facts: no 
  
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  
  vars_files: 
    - vcenter_vars.yml

  tasks: 
    - name: Gather info about ESXi Host
      community.vmware.vmware_host_facts:
        hostname: '{{ vcenter_server }}'
        username: '{{ vcenter_user }}'
        password: '{{ vcenter_pass }}'
        validate_certs: no
        esxi_hostname: '{{ esxi_hostname }}'
      delegate_to: localhost
      register: hosts

    - debug:
        msg: "{{ hosts.ansible_facts }}"
      #when: "true == hosts.ansible_facts.ansible_in_maintenance_mode" 

    
    