---
- hosts: localhost 
  gather_facts: no 
  
  vars:
    - ansible_python_interpreter: /usr/bin/python3
  
  vars_files: 
    - vcenter_vars.yml

  tasks:
    - name: Enter VSAN-Compliant Maintenance Mode
      community.vmware.vmware_maintenancemode:
        hostname: "{{ vcenter_server }}"
        username: "{{ vcenter_user }}"
        password: "{{ vcenter_pass }}"
        validate_certs: no
        esxi_hostname: "{{ esxi_hostname }}"
        vsan: ensureObjectAccessibility
        evacuate: true
        timeout: 3600
        state: present 
      register: maintenance
    
    - debug:
        msg: "{{ maintenance }}"