---
- hosts: 10.65.190.227 
  gather_facts: no 
  
  vars:
    - ansible_python_interpreter: /usr/bin/python3
   
  tasks:  
  - name: Reboot the server 
    shell: reboot

  - name: Wait for the reboot to complete if there was a change.
    wait_for_connection:
      connect_timeout: 10
      sleep: 10
      delay: 10
      timeout: 300
  
  - ping: