---
# tasks file for folders
- name: Get folders from vCenter
  uri:
    url: https://{{ vcenter_server }}/rest/vcenter/folder
    force_basic_auth: yes
    validate_certs: "{{ validate_certs }}"
    headers:
      Cookie: "{{ login.set_cookie }}"
  register: vfolders

- name: Print names of folders in the given vCenter
  debug:
    msg: "{{ item.name }}"
  with_items: "{{ vfolders.json.value }}"