---
# tasks file for datacenters
- name: Get datacenters from vCenter
  uri:
    url: https://{{ vcenter_server }}/rest/vcenter/datacenter
    force_basic_auth: yes
    validate_certs: "{{ validate_certs }}"
    headers:
      Cookie: "{{ login.set_cookie }}"
  register: vDatacenters

- name: Print names of datacenters in the given vCenter
  debug:
    msg: "{{ item.name }}"
  with_items: "{{ vDatacenters.json.value }}"