---
- name: Gather all Categories for vCenter
  hosts: localhost  
  gather_facts: no
  vars_files:
    - vcenter_vars.yaml
 
  roles:
    - login
    - categories
    - clusters
    - datacenters
    - datastores
    - folders
    - hosts
    - networks
    - tags
    - vms