---
# tasks file for vms
- name: Get VMs from vCenter
  uri:
    url: https://{{ vcenter_server }}/rest/vcenter/vm
    force_basic_auth: yes
    validate_certs: "{{ validate_certs }}"
    headers:
      Cookie: "{{ login.set_cookie }}"
  register: vVMs

- name: Print names of VMs in the given vCenter
  debug:
    msg: "{{ item.name }}"
  with_items: "{{ vVMs.json.value }}"